name: pr-title-caller

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, assigned, unassigned]

permissions:
  contents: read
  pull-requests: read

jobs:
  pr-title:
    uses: ./.github/workflows/pr-title.yml
